name: Django CI

on:
  push:
    branches: [ danial/add-unit-tests-github-actions ]
  pull_request:
    branches: [ danial/add-unit-tests-github-actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: DEBUG
      run: |
        echo $(python --version)
        echo $(pip --version)
        echo $(which python)
        echo $(python -m urlparse)
    - name: start docker container
      run: |
        docker-compose -f ./.github/docker-compose-github.yml up -d
    - name: DEBUG containers
      run: |
        docker ps -a
    - name: Install Dependencies
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && cd /edx/app/ecommerce/ecommerce/ && make requirements'
    - name: DEBUG 2
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && echo $(python --version)'
        docker exec -t ecommerce_testing bash -c 'echo $(pip --version)'
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env &&  echo $(which python)'
        docker exec -t ecommerce_testing bash -c 'echo $(python -m urlparse)'
    - name: Make html
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && cd /edx/app/ecommerce/ecommerce/docs && make html'
    - name: Make clean static
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && cd /edx/app/ecommerce/ecommerce/ && DJANGO_SETTINGS_MODULE=ecommerce.settings.test make clean_static'
    - name: Make static
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && cd /edx/app/ecommerce/ecommerce/ && make requirements && DJANGO_SETTINGS_MODULE=ecommerce.settings.test make static'
    - name: Run Tests
      run: |
        docker exec -t ecommerce_testing bash -c 'source /edx/app/ecommerce/ecommerce_env && cd /edx/app/ecommerce/ecommerce/ && DJANGO_SETTINGS_MODULE=ecommerce.settings.test TRAVIS=1 xvfb-run make validate_python'
